### ISSUE TITLE
Please add a database section

### ISSUE THREAD

**Issue by adrianjw** [mxssl/sre-interview-prep-guide#13]
Please consider adding a database section as most SRE job interviews will ask you some database questions.

List of database topics:
- [Types of database paradigms](https://www.youtube.com/watch?v=W2Z7fbCLSTw)
- SQL vs NoSQL
- [CAP theorem](https://en.wikipedia.org/wiki/CAP_theorem)
- [ACID vs BASE properties](https://medium.com/geekculture/acid-vs-base-in-databases-1bcad774da26)
- Database sharding, indexing, caching, replication, scalability

**Comment by mxssl** [comment]
https://github.com/mxssl/sre-interview-prep-guide/blob/master/README.md#databases
