### ISSUE TITLE
More blogs for debugging section

### ISSUE THREAD

**Issue by akshatgit** [mxssl/sre-interview-prep-guide#22]
Hi, Thanks for the great prep guide. I've found some more debugging blogs and I think they will be useful. 
- strace: https://www.dedoimedo.com/computers/strace.html
- lsof: https://www.dedoimedo.com/computers/lsof.html
- combination of strace, ltrace, lsof and vmstat: https://www.dedoimedo.com/computers/linux-system-debugging-super.html

**Comment by mxssl** [comment]
Added to troubleshooting section: https://github.com/mxssl/sre-interview-prep-guide/blob/master/README.md#troubleshooting

Thank you!

**Comment by akshatgit** [comment]
There is a practice website I found for solving troubleshooting. https://sadservers.com/
we can add this also to the list.
